### ISSUE TITLE
OFF Files created by GMML segfault tleap. Might be only glycoproteins.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/GMML#105]

**Comment by Lachele** [comment]
Easy thing to check:  Did you give the system in the OFF file a name?  This would correspond to 'CONDENSEDSEQUENCE', the default for oligosaccharide builds.  If that isn't set, leap will probably lose its cookies.

If that's not the issue, please post a sample off file.  Small is better.  Maybe build just a 3-amio acid peptide with a DGlcpb attached to an ASN in the middle and see if that segfaults.
