### ISSUE TITLE
PDB Preprocessor SegFault error for 2n7b

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/GMML#119]
The api receives a JSONServer error when we try to preprocess 2n7b. Evaluation works without error.
API logging of response:
```
{"preprocess": {"type": "PreprocessPdbForAmber"}}, "inputs": {"pdb_ID": "2n7b"}}, "options": {"targetModule": "amber"}}
2021-12-02 12:10:22 PM - json_api.json_api - INFO - submit() was called.

2021-12-02 12:10:24 PM - json_api.json_api - DEBUG - 
Response Time: 3.0278999474830925e-05
2021-12-02 12:10:24 PM - pdb.views - DEBUG - The response:
2021-12-02 12:10:24 PM - json_api.json_api - INFO - prettyPrint() was called.
2021-12-02 12:10:24 PM - json_api.json_api - DEBUG - 
{
    "entity": {
        "type": "GRPC",
        "responses": [
            {
                "Error": {
                    "respondingService": "JSONServer",
                    "notice": {
                        "type": "Exit",
                        "code": "7",
                        "brief": "CaughtSegFault",
                        "message": "A subprocess generated a segmentation fault."
                    },
                    "options": {
                        "osExitCode": "139",
                        "theStandardError": "b'Segmentation fault (core dumped)\\n'",
                        "theStandardOutput": "b''",
                        "theExceptionError": "None"
                    }
                }
            }
        ]
    }
}
```

I don't see any other interesting logs. Happy to hunt them down with direction.

**Comment by gitoliver** [comment]
This segfaults the old and new preprocessor. Removing the CONECT entries stops the segfault. There are 20 models in here, and the CONECT entries would have to apply to each one. This will take a bit of digging.

**Comment by gitoliver** [comment]
The CONECT cards existing their own modeling section after an ENDMDL and before the END created an empty assembly. We ignore CONECT anyway so easy fix in the new central data structure classes. Added 2n7b to the 019 gmml test. Pushed fix to gmml-test. The old gmml PdbPreprocessor code used by the website will still choke on this, but it will switch to new code asap so no plans to fix it.
