### ISSUE TITLE
PDBs that contain OXT cannot be preprocessed. OXT causes Unrecognized Atom error

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/GMML#120]
I see this when using pdb preprocessor tool to sideload 3UES and 3UET from RCSB.org
![3UES_errors](https://user-images.githubusercontent.com/27075406/144471950-30ca9b80-7662-44b9-b3df-99444e832f2e.png)

**Comment by gitoliver** [comment]
Fixed in the new pdbprocessor https://github.com/GLYCAM-Web/gmml/blob/gmml-test/includes/CentralDataStructure/Readers/Pdb/pdbModel.hpp
