### ISSUE TITLE
Items slated for deprecation

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/GMML#81]
Issues in the "Slated for deprecation" milestone are items that should be deprecated.

Each issue should clearly state what is to be deprecated, a brief explanation of why, and a time after which it should become deprecated.  One issue can contain multiple entries, particularly if they all go together. Other information might be added as appropriate or desired.  In the code itself, if possible, use of the item should produce an appropriate warning message about the upcoming deprecation.

For example, functions that have inappropriate dependencies might be deprecated.  These are functions that require more input than they should or that require the wrong input.  

For example, here a function for getting your car's oil changed that requires more than expected:
`ChangeOil(Vehicle car-type, Weight oil-weight, Cat cat-type)`
Here, it seems quite unlikely that your cat is needed for getting your car's oil changed.  Even if you argue that the cat keeps mice from nesting in the engine block, that is really another category of maintenance.  

Note that the deprecation applies only to the exact thing specified, here an entire call.  For example:
`ChangeOil(Vehicle sedan, Weight 5w30, Cat tabby)  ## deprecated; going away`
`ChangeOil(Vehicle sedan, Weight 5w30) ## NOT deprecated; staying`

The issue might say something like:

> Item to deprecate:
> `ChangeOil(Vehicle sedan, Weight 5w30, Cat tabby)`

> Reason:  A cat is not generally relevant to an oil change.

> Deprecate by:  2018-04-01

**Comment by gitoliver** [comment]
Too many cat examples.
