### ISSUE TITLE
PDB reader/writer should be able to handle HETATM cards in middle of ATOM cards

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/GMML#93]
Example PDBID: 1d2v
Problem section is pasted below. When I load this into my Glycoprotein Builder code, the output file is missing all residues in the C chain up to residue 150. 

This is how non-natural or modified amino acids are written into PDB files, so we need to support it.   

ATOM   1126  N   SER C 149      13.855 -13.122   7.580  1.00  3.66           N
ATOM   1127  CA  SER C 149      15.243 -13.464   7.845  1.00  3.78           C
ATOM   1128  C   SER C 149      15.419 -13.682   9.345  1.00  2.98           C
ATOM   1129  O   SER C 149      14.809 -12.973  10.149  1.00  2.00           O
ATOM   1130  CB  SER C 149      16.157 -12.332   7.378  1.00  3.99           C
ATOM   1131  OG  SER C 149      16.131 -12.192   5.969  1.00  4.88           O
HETATM 1132  N   CSO C 150      16.226 -14.682   9.724  1.00  2.67           N
HETATM 1133  CA  CSO C 150      16.468 -14.991  11.137  1.00  5.53           C
HETATM 1134  CB  CSO C 150      17.483 -16.121  11.260  1.00  6.96           C
HETATM 1135  SG  CSO C 150      16.962 -17.687  10.515  1.00  9.03           S
HETATM 1136  C   CSO C 150      17.000 -13.770  11.897  1.00  5.30           C
HETATM 1137  O   CSO C 150      17.940 -13.101  11.432  1.00  6.13           O
HETATM 1138  OD  CSO C 150      16.181 -18.345  11.550  1.00  7.90           O
ATOM   1139  N   PRO C 151      16.396 -13.449  13.066  1.00  6.15           N
ATOM   1140  CA  PRO C 151      16.824 -12.312  13.892  1.00  6.11           C
ATOM   1141  C   PRO C 151      18.119 -12.672  14.634  1.00  6.84           C
ATOM   1142  O   PRO C 151      18.299 -13.823  15.065  1.00  6.70           O
ATOM   1143  CB  PRO C 151      15.643 -12.108  14.832  1.00  6.06           C
ATOM   1144  CG  PRO C 151      15.157 -13.508  15.047  1.00  7.57           C
ATOM   1145  CD  PRO C 151      15.236 -14.151  13.687  1.00  7.46           C

**Comment by Lachele** [comment]
I totally agree.  Is there anyone who has the knowledge already to have a shot at doing it quickly?  Do any of those people have enough time available to do it?  Is this super-high priority?

In the meantime, there must be some workaround using sed or such, like if the line before is atom, change to hetatm. If not (if it is ter, etc.), don't change it.  Maybe.

**Comment by gitoliver** [comment]
I'm creating a list of issues that are for later. It isn't high priority
yet. I just want to define the issues as best I can and preserve them.
Oliver

**Comment by gitoliver** [comment]
Added ability to check for this in new pdbPreprocessor. There is now an entry in includes/CentralDataStructure/Readers/Pdb/pdbPreprocessorInputs.hpp that can be shown to the user for nonNatural protein residues. Should be available as of gmml commit 787a21ffe36cf5ea9169cbdaf4767d4da985b2e3. Added PDBID 1d2v to test 019.
